/**
 * @description Tests unitarios de ReflectionEngine — sin disco real.
 * Mockea FailureCatalog, PatternDetector, PolicyPromoter y fs/promises
 * para cubrir branches no alcanzados por los tests de integracion.
 */

import { ReflectionEngine } from '../../src/reflection/reflection-engine';
import { FailureCatalog } from '../../src/reflection/failure-catalog';
import { PatternDetector } from '../../src/reflection/pattern-detector';
import { PolicyPromoter } from '../../src/reflection/policy-promoter';
import { DetectedPattern, ManifestPolicyRule, ReflectionDomain } from '../../src/reflection/types';

// ── Mocks ────────────────────────────────────────────────────────────────────

jest.mock('../../src/reflection/failure-catalog');
jest.mock('../../src/reflection/pattern-detector');
jest.mock('../../src/reflection/policy-promoter');
jest.mock('../../src/memory/updater', () => ({
  updateProjectContext: jest.fn().mockResolvedValue(undefined),
  updateEngineInsights: jest.fn().mockResolvedValue(undefined),
}));

jest.mock('fs/promises', () => ({
  readFile: jest.fn().mockResolvedValue(''),
  mkdir: jest.fn().mockResolvedValue(undefined),
}));

jest.mock('../../src/shared/utils/atomic-write', () => ({
  atomicWrite: jest.fn().mockResolvedValue(undefined),
}));

const MockFailureCatalog = FailureCatalog as jest.MockedClass<typeof FailureCatalog>;
const MockPatternDetector = PatternDetector as jest.MockedClass<typeof PatternDetector>;
const MockPolicyPromoter = PolicyPromoter as jest.MockedClass<typeof PolicyPromoter>;

// ── Helpers ──────────────────────────────────────────────────────────────────

function makePattern(overrides: Partial<DetectedPattern> = {}): DetectedPattern {
  return {
    failureType: 'connection_leak',
    domain: 'audit',
    count: 5,
    firstSeen: '2026-01-01',
    lastSeen: '2026-01-05',
    severity: 'high',
    recordIds: ['1', '2', '3', '4', '5'],
    dominantDimension: 'seguridad',
    dominantGate: 'qa',
    recommendedAction: 'Fix it',
    promotedToPolicy: false,
    ...overrides,
  };
}

function makeRule(overrides: Partial<ManifestPolicyRule> = {}): ManifestPolicyRule {
  return {
    id: 'POL-AUDI-001',
    name: '[Audit] Connection Leak',
    if: { keywords: ['connection'] },
    then: { requireQaApproval: true },
    trigger: { domain: 'audit', pattern: 'connection_leak', minOccurrences: 3 },
    autoGenerated: true,
    createdAt: '2026-01-05T00:00:00.000Z',
    engineVersion: '1.0.0',
    ...overrides,
  };
}

// ── Tests ────────────────────────────────────────────────────────────────────

describe('ReflectionEngine — unit tests', () => {
  let engine: ReflectionEngine;
  let mockCatalog: jest.Mocked<FailureCatalog>;
  let mockDetector: jest.Mocked<PatternDetector>;
  let mockPromoter: jest.Mocked<PolicyPromoter>;

  beforeEach(() => {
    jest.clearAllMocks();

    // Setup mocks
    mockCatalog = {
      load: jest.fn().mockResolvedValue(undefined),
      addRecord: jest.fn().mockResolvedValue({}),
      getDomainCounts: jest.fn().mockResolvedValue({ audit: 0, test: 0, commit: 0, agent: 0, bootstrap: 0 }),
      totalRecords: jest.fn().mockResolvedValue(0),
      findUnresolved: jest.fn().mockResolvedValue([]),
      findByDomain: jest.fn().mockResolvedValue([]),
    } as any;

    mockDetector = {
      scanByDomain: jest.fn().mockImplementation(async (domain: string) => {
        // Solo devolver patrones para el dominio 'audit' en tests que lo necesitan
        return [];
      }),
    } as any;

    mockPromoter = {
      findRule: jest.fn().mockResolvedValue(undefined),
      promote: jest.fn().mockResolvedValue(makeRule()),
      getExistingRules: jest.fn().mockResolvedValue([]),
    } as any;

    (MockFailureCatalog as any).mockImplementation(() => mockCatalog);
    (MockPatternDetector as any).mockImplementation(() => mockDetector);
    (MockPolicyPromoter as any).mockImplementation(() => mockPromoter);

    engine = new ReflectionEngine({
      projectRoot: '/tmp/test',
      useGlobalDir: false,
      config: { autoPromote: true, promotionThreshold: 3 },
    });
  });

  describe('reflect() — H-05 autoPromote logic', () => {
    it('should skip unknown_ failureTypes during autoPromote', async () => {
      mockDetector.scanByDomain.mockResolvedValue([
        makePattern({ failureType: 'unknown_agent', severity: 'high', count: 5 }),
      ]);

      const result = await engine.reflect({ autoPromote: true });

      expect(result.promotedRules).toHaveLength(0);
      expect(mockPromoter.promote).not.toHaveBeenCalled();
    });

    it('should skip patterns with severity Baja or Media during autoPromote', async () => {
      mockDetector.scanByDomain.mockResolvedValue([
        makePattern({ failureType: 'connection_leak', severity: 'low', count: 5 }),
        makePattern({ failureType: 'missing_logging', severity: 'medium', count: 5 }),
      ]);

      const result = await engine.reflect({ autoPromote: true });

      expect(result.promotedRules).toHaveLength(0);
      expect(mockPromoter.promote).not.toHaveBeenCalled();
    });

    it('should skip patterns below promotionThreshold during autoPromote', async () => {
      mockDetector.scanByDomain.mockResolvedValue([
        makePattern({ failureType: 'connection_leak', severity: 'high', count: 2 }),
      ]);

      const result = await engine.reflect({ autoPromote: true, threshold: 3 });

      expect(result.promotedRules).toHaveLength(0);
      expect(mockPromoter.promote).not.toHaveBeenCalled();
    });

    it('should promote patterns that pass all filters', async () => {
      mockDetector.scanByDomain.mockImplementation(async (domain: string) => {
        if (domain === 'audit') {
          return [makePattern({ failureType: 'connection_leak', severity: 'high', count: 5 })];
        }
        return [];
      });
      mockPromoter.promote.mockResolvedValue(makeRule({ id: 'POL-AUDI-001' }));

      const result = await engine.reflect({ autoPromote: true });

      expect(result.promotedRules).toHaveLength(1);
      expect(mockPromoter.promote).toHaveBeenCalledTimes(1);
    });

    it('should skip already-promoted patterns (existing rule found)', async () => {
      mockDetector.scanByDomain.mockImplementation(async (domain: string) => {
        if (domain === 'audit') {
          return [makePattern({ failureType: 'connection_leak', severity: 'high', count: 5 })];
        }
        return [];
      });
      mockPromoter.findRule.mockResolvedValue(makeRule({ id: 'POL-AUDI-001' }));

      const result = await engine.reflect({ autoPromote: true });

      expect(result.promotedRules).toHaveLength(0);
      expect(mockPromoter.promote).not.toHaveBeenCalled();
      // Pattern should be marked as promoted
      expect(result.patterns[0].promotedToPolicy).toBe(true);
      expect(result.patterns[0].policyRuleId).toBe('POL-AUDI-001');
    });

    it('should not promote when autoPromote is false', async () => {
      mockDetector.scanByDomain.mockImplementation(async (domain: string) => {
        if (domain === 'audit') {
          return [makePattern({ failureType: 'connection_leak', severity: 'high', count: 5 })];
        }
        return [];
      });

      const result = await engine.reflect({ autoPromote: false });

      expect(result.promotedRules).toHaveLength(0);
      expect(mockPromoter.promote).not.toHaveBeenCalled();
    });

    it('should not promote when engine is disabled', async () => {
      engine = new ReflectionEngine({
        projectRoot: '/tmp/test',
        useGlobalDir: false,
        config: { autoPromote: true, enabled: false },
      });

      mockDetector.scanByDomain.mockImplementation(async (domain: string) => {
        if (domain === 'audit') {
          return [makePattern({ failureType: 'connection_leak', severity: 'high', count: 5 })];
        }
        return [];
      });

      const result = await engine.reflect({ autoPromote: true });

      expect(result.promotedRules).toHaveLength(0);
      expect(mockPromoter.promote).not.toHaveBeenCalled();
    });

    it('should not promote when maxAutoGeneratedRules is reached', async () => {
      // Simular que ya hay 20 reglas auto-generadas en el manifest
      const existingRules = Array.from({ length: 20 }, (_, i) => makeRule({
        id: `POL-AUDI-${String(i + 1).padStart(3, '0')}`,
        autoGenerated: true,
      }));
      mockPromoter.getExistingRules.mockResolvedValue(existingRules);

      mockDetector.scanByDomain.mockImplementation(async (domain: string) => {
        if (domain === 'audit') {
          return [makePattern({ failureType: 'connection_leak', severity: 'high', count: 5 })];
        }
        return [];
      });

      const result = await engine.reflect({ autoPromote: true });

      expect(result.promotedRules).toHaveLength(0);
      expect(mockPromoter.promote).not.toHaveBeenCalled();
    });

    it('should promote when below maxAutoGeneratedRules limit', async () => {
      // Simular que hay 19 reglas auto-generadas (1 slot libre)
      const existingRules = Array.from({ length: 19 }, (_, i) => makeRule({
        id: `POL-AUDI-${String(i + 1).padStart(3, '0')}`,
        autoGenerated: true,
      }));
      mockPromoter.getExistingRules.mockResolvedValue(existingRules);
      mockPromoter.promote.mockResolvedValue(makeRule({ id: 'POL-AUDI-020' }));

      mockDetector.scanByDomain.mockImplementation(async (domain: string) => {
        if (domain === 'audit') {
          return [makePattern({ failureType: 'connection_leak', severity: 'high', count: 5 })];
        }
        return [];
      });

      const result = await engine.reflect({ autoPromote: true });

      expect(result.promotedRules).toHaveLength(1);
      expect(mockPromoter.promote).toHaveBeenCalledTimes(1);
    });

    it('should respect maxAutoGeneratedRules across multiple patterns in same batch', async () => {
      // Simular que hay 19 reglas auto-generadas (1 slot libre)
      const existingRules = Array.from({ length: 19 }, (_, i) => makeRule({
        id: `POL-AUDI-${String(i + 1).padStart(3, '0')}`,
        autoGenerated: true,
      }));
      mockPromoter.getExistingRules.mockResolvedValue(existingRules);
      mockPromoter.promote.mockResolvedValue(makeRule({ id: 'POL-AUDI-020' }));

      // 2 patrones elegibles, pero solo 1 slot libre
      mockDetector.scanByDomain.mockImplementation(async (domain: string) => {
        if (domain === 'audit') {
          return [
            makePattern({ failureType: 'connection_leak', severity: 'high', count: 5 }),
            makePattern({ failureType: 'security_vulnerability', severity: 'critical', count: 4 }),
          ];
        }
        return [];
      });

      const result = await engine.reflect({ autoPromote: true });

      // Solo 1 debe promoverse (el primero), el segundo se salta por el limite
      expect(result.promotedRules).toHaveLength(1);
      expect(mockPromoter.promote).toHaveBeenCalledTimes(1);
    });
  });

  describe('reflect() — domain filtering', () => {
    it('should scan only the specified domain', async () => {
      mockDetector.scanByDomain.mockResolvedValue([]);

      await engine.reflect({ domain: 'test' });

      expect(mockDetector.scanByDomain).toHaveBeenCalledWith('test', 3);
    });

    it('should scan all active domains when no domain specified', async () => {
      mockDetector.scanByDomain.mockResolvedValue([]);

      await engine.reflect();

      // Should scan all 5 domains (audit, test, commit, agent, bootstrap)
      // Nota: calculateStats() tambien llama a scanByDomain, por eso son 10
      expect(mockDetector.scanByDomain).toHaveBeenCalledWith('audit', 3);
      expect(mockDetector.scanByDomain).toHaveBeenCalledWith('test', 3);
      expect(mockDetector.scanByDomain).toHaveBeenCalledWith('commit', 3);
      expect(mockDetector.scanByDomain).toHaveBeenCalledWith('agent', 3);
      expect(mockDetector.scanByDomain).toHaveBeenCalledWith('bootstrap', 3);
    });
  });

  describe('reportIncident() — H-08 failureType validation', () => {
    it('should generate an ID and add record to catalog', async () => {
      mockCatalog.addRecord.mockResolvedValue({});

      const result = await engine.reportIncident({
        domain: 'audit',
        failureType: 'connection_leak',
        severity: 'high',
        dimension: 'seguridad',
        gate: 'qa',
        agenteResponsable: 'qa',
        hallazgo: 'test',
        recomendacion: 'fix',
        archivos: [],
        fecha: new Date().toISOString(),
      });

      expect(result.record.id).toMatch(/^fail_/);
      expect(mockCatalog.addRecord).toHaveBeenCalledTimes(1);
    });

    it('should return empty patterns array', async () => {
      mockCatalog.addRecord.mockResolvedValue({});

      const result = await engine.reportIncident({
        domain: 'audit',
        failureType: 'connection_leak',
        severity: 'high',
        dimension: 'seguridad',
        gate: 'qa',
        agenteResponsable: 'qa',
        hallazgo: 'test',
        recomendacion: 'fix',
        archivos: [],
        fecha: new Date().toISOString(),
      });

      expect(result.patterns).toEqual([]);
    });
  });

  describe('flushReflections()', () => {
    it('should process all pending reflections', async () => {
      mockDetector.scanByDomain.mockResolvedValue([]);

      // Report incidents to create pending reflections
      await engine.reportIncident({
        domain: 'audit', failureType: 'connection_leak', severity: 'high',
        dimension: 'seguridad', gate: 'qa', agenteResponsable: 'qa',
        hallazgo: 'test', recomendacion: 'fix', archivos: [], fecha: new Date().toISOString(),
      });
      await engine.reportIncident({
        domain: 'test', failureType: 'jest_timeout', severity: 'high',
        dimension: 'rendimiento', gate: 'jest', agenteResponsable: 'system',
        hallazgo: 'test', recomendacion: 'fix', archivos: [], fecha: new Date().toISOString(),
      });

      const result = await engine.flushReflections();

      expect(result.patterns).toBeDefined();
      expect(result.promotedRules).toBeDefined();
      // Should have scanned 2 domains (audit, test) — flushReflections llama a reflectByDomain
      // que llama a reflect() que llama a scanByDomain + calculateStats (otra vez scanByDomain)
      // Total: 2 dominios * 2 llamadas = 4
      expect(mockDetector.scanByDomain).toHaveBeenCalledWith('audit', 3);
      expect(mockDetector.scanByDomain).toHaveBeenCalledWith('test', 3);
    });

    it('should return empty when no pending reflections', async () => {
      const result = await engine.flushReflections();

      expect(result.patterns).toEqual([]);
      expect(result.promotedRules).toEqual([]);
    });
  });

  describe('connectMemory() / getProjectDir()', () => {
    it('should store and return project directory', () => {
      expect(engine.getProjectDir()).toBeUndefined();
      engine.connectMemory('/some/project');
      expect(engine.getProjectDir()).toBe('/some/project');
    });
  });

  describe('getLessonsMemoPath()', () => {
    it('should return a valid path', () => {
      const path = engine.getLessonsMemoPath();
      expect(path).toContain('.deepseek-code');
      expect(path).toContain('lecciones-aprendidas.md');
    });
  });

  describe('getLastPatterns() / getLastPromotedRules()', () => {
    it('should return empty arrays before any reflect()', () => {
      expect(engine.getLastPatterns()).toEqual([]);
      expect(engine.getLastPromotedRules()).toEqual([]);
    });

    it('should return patterns and rules after reflect()', async () => {
      mockDetector.scanByDomain.mockImplementation(async (domain: string) => {
        if (domain === 'audit') {
          return [makePattern({ failureType: 'connection_leak', severity: 'high', count: 5 })];
        }
        return [];
      });
      mockPromoter.promote.mockResolvedValue(makeRule({ id: 'POL-AUDI-001' }));

      await engine.reflect({ autoPromote: true });

      expect(engine.getLastPatterns()).toHaveLength(1);
      expect(engine.getLastPromotedRules()).toHaveLength(1);
    });
  });

  describe('getCatalog() / getDetector() / getPromoter()', () => {
    it('should return the internal instances', () => {
      expect(engine.getCatalog()).toBe(mockCatalog);
      expect(engine.getDetector()).toBe(mockDetector);
      expect(engine.getPromoter()).toBe(mockPromoter);
    });
  });

  describe('reflectByDomain()', () => {
    it('should delegate to reflect() with domain', async () => {
      mockDetector.scanByDomain.mockResolvedValue([]);

      const result = await engine.reflectByDomain('commit');

      expect(mockDetector.scanByDomain).toHaveBeenCalledWith('commit', 3);
      expect(result.patterns).toBeDefined();
      expect(result.promotedRules).toBeDefined();
    });
  });
});
