/**
 * @description Integración: verifica el ciclo completo policy round-trip:
 * reportar incidentes → detectar patrón → promover policy → orquestador la aplica.
 */

import * as os from 'os';
import * as path from 'path';
import * as fs from 'fs';
import * as yaml from 'yaml';
import { ReflectionEngine } from '../../src/reflection/reflection-engine';
import { PolicyPromoter } from '../../src/reflection/policy-promoter';
import { applyPolicies } from '../../src/orchestrator/policy-engine';
import { PolicyRule } from '../../src/orchestrator/types';
import { TaskContext } from '../../src/types/task-context';

describe('Policy Round-Trip — incidente → patrón → policy → orquestador', () => {
  let tmpDir: string;
  let originalHome: string | undefined;
  let originalUserProfile: string | undefined;
  let engine: ReflectionEngine;

  beforeEach(async () => {
    tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'policy-rt-test-'));
    originalHome = process.env.HOME;
    originalUserProfile = process.env.USERPROFILE;
    process.env.HOME = tmpDir;
    process.env.USERPROFILE = tmpDir;

    engine = new ReflectionEngine({ projectRoot: tmpDir, useGlobalDir: true });
    await engine.initialize();
  });

  afterEach(() => {
    process.env.HOME = originalHome;
    process.env.USERPROFILE = originalUserProfile;
    fs.rmSync(tmpDir, { recursive: true, force: true });
  });

  it('3 incidentes del mismo tipo generan un patrón detectado', async () => {
    const fecha = new Date().toISOString();

    for (let i = 0; i < 3; i++) {
      await engine.reportIncident({
        fecha,
        dominio: 'audit',
        domain: 'audit',
        failureType: 'hardcoded_secret',
        dimension: 'Seguridad',
        gate: 'security',
        severity: 'high',
        descripcion: `API key hardcodeada detectada (ocurrencia ${i + 1})`,
        recomendacion: 'Usar variables de entorno para credenciales',
        archivoAfectado: 'src/config.ts',
      });
    }

    const { patterns } = await engine.flushReflections();
    expect(patterns.length).toBeGreaterThanOrEqual(1);

    const hardcodedPattern = patterns.find(p => p.failureType === 'hardcoded_secret');
    expect(hardcodedPattern).toBeDefined();
    expect(hardcodedPattern!.count).toBeGreaterThanOrEqual(3);
  });

  it('flushReflections() promueve el patrón a policyRule en manifest.yaml', async () => {
    const fecha = new Date().toISOString();

    for (let i = 0; i < 3; i++) {
      await engine.reportIncident({
        fecha,
        dominio: 'test',
        domain: 'test',
        failureType: 'jest_timeout',
        dimension: 'Testing',
        gate: 'qa',
        severity: 'high',
        descripcion: `Jest timeout en suite ${i + 1}`,
        recomendacion: 'Aumentar timeout o usar test doubles',
        archivoAfectado: 'tests/integration/slow.test.ts',
      });
    }

    const { promotedRules } = await engine.flushReflections();

    // Verificar que se promovió al menos una regla
    expect(promotedRules.length).toBeGreaterThanOrEqual(1);
    const promoted = promotedRules[0];
    expect(promoted.autoGenerated).toBe(true);
    expect(promoted.trigger.domain).toBe('test');
    expect(promoted.trigger.pattern).toBe('jest_timeout');
  });

  it('manifest.yaml escrito por PolicyPromoter contiene la policyRule', async () => {
    const promoter = new PolicyPromoter({
      manifestPath: path.join(tmpDir, '.deepseek-code', 'manifest.yaml'),
    });
    const fecha = new Date().toISOString();

    for (let i = 0; i < 3; i++) {
      await engine.reportIncident({
        fecha,
        dominio: 'commit',
        domain: 'commit',
        failureType: 'commit_without_tests',
        dimension: 'Testing',
        gate: 'qa',
        severity: 'high',
        descripcion: `Commit sin tests (${i + 1})`,
        recomendacion: 'Asegurar al menos un test por cambio de lógica',
        archivoAfectado: 'src/core/service.ts',
      });
    }

    await engine.flushReflections();

    // Verificar manifest.yaml
    const manifestPath = path.join(tmpDir, '.deepseek-code', 'manifest.yaml');
    expect(fs.existsSync(manifestPath)).toBe(true);

    const content = fs.readFileSync(manifestPath, 'utf-8');
    const manifest = yaml.parse(content);
    expect(manifest.policyRules).toBeDefined();
    expect(manifest.policyRules.length).toBeGreaterThanOrEqual(1);

    const rule = manifest.policyRules.find((r: any) => r.trigger?.pattern === 'commit_without_tests');
    expect(rule).toBeDefined();
  });

  it('applyPolicies() aplica la regla promovida a una tarea que hace match', async () => {
    // Simular una regla auto-promovida (como lo haría el PolicyPromoter)
    const customRules: PolicyRule[] = [
      {
        if: { actionType: 'implementation' },
        then: { mustInclude: ['qa-engineer'], requireQaApproval: true },
      },
    ];

    const task: TaskContext = {
      id: 'task-001',
      description: 'Implementar nuevo endpoint de autenticación',
      actionType: 'implementation',
      domains: ['backend'],
      riskLevel: 'medium',
      status: 'pending',
      assignedAgents: [],
      requiresQaApproval: false,
      requiresSecurityReview: false,
      requiresArchitectureReview: false,
      hopCount: 0,
      filesModified: [],
      riskFactors: {
        breaking_change: false,
        security_sensitive: false,
        cross_service_impact: false,
        db_transactional: false,
        production_critical: false,
      },
    };

    const { result } = applyPolicies(task, customRules);

    expect(result.appliedRules.length).toBeGreaterThanOrEqual(1);
    expect(result.mustInclude).toContain('qa-engineer');
  });

  it('updateOutcome() persiste telemetría de éxito/fallo en manifest', async () => {
    const manifestPath = path.join(tmpDir, '.deepseek-code', 'manifest.yaml');
    const promoter = new PolicyPromoter({ manifestPath });

    // Promover una regla directamente
    const fecha = new Date().toISOString();
    for (let i = 0; i < 3; i++) {
      await engine.reportIncident({
        fecha,
        dominio: 'agent',
        domain: 'agent',
        failureType: 'agent_hallucination',
        dimension: 'Calidad',
        gate: 'qa',
        severity: 'high',
        descripcion: `Alucinación de agente (${i + 1})`,
        recomendacion: 'Habilitar LogicEvaluator para detectar inventos',
        archivoAfectado: '',
      });
    }
    const { promotedRules } = await engine.flushReflections();
    expect(promotedRules.length).toBeGreaterThanOrEqual(1);

    const ruleId = promotedRules[0].id;

    await promoter.updateOutcome(ruleId, 'success');
    await promoter.updateOutcome(ruleId, 'success');
    await promoter.updateOutcome(ruleId, 'failure');

    const rule = await promoter.getRuleById(ruleId);
    expect(rule?.outcomes).toBeDefined();
    expect(rule!.outcomes!.success).toBe(2);
    expect(rule!.outcomes!.failure).toBe(1);
  });
});
