/**
 * @description Tests del Reflection Engine — Fase 1 completa.
 *
 * Cubre:
 * 1. Types (FailureRecord, DetectedPattern, helpers)
 * 2. FailureCatalog (CRUD, persistencia, consultas)
 * 3. PatternDetector (detección de patrones ≥3 ocurrencias)
 * 4. PolicyPromoter (lectura/escritura de manifest.yaml)
 * 5. ReflectionEngine (pipeline completo)
 * 6. Dominios (audit, test, commit, agent, bootstrap)
 * 7. Hooks (AuditHook, TestHook, CommitHook, AgentHook, BootstrapHook)
 * 8. Integración AuditReporter → ReflectionEngine
 */

import * as path from 'path';
import * as os from 'os';
import * as fs from 'fs';

// ── Tipos y clases del Reflection Engine ──────────────────────────────────

import {
  // Tipos
  ReflectionDomain,
  FailureType,
  FailureRecord,
  DetectedPattern,
  ManifestPolicyRule,
  FAILURE_TYPES_BY_DOMAIN,
  generateFailureId,
  generatePolicyRuleId,
  defaultReflectionConfig,

  // Core
  FailureCatalog,
  PatternDetector,
  PolicyPromoter,
  ReflectionEngine,

  // Dominios
  detectAuditFailureType,
  getAuditFailureTypeMeta,
  AuditFailureTypeMeta,
  detectTestFailureType,
  detectCommitFailureType,
  detectAgentFailureType,
  detectBootstrapFailureType,

  // Hooks
  AuditHook,
  TestHook,
  CommitHook,
  AgentHook,
  BootstrapHook,
} from '../../src/reflection';

// ── Loaders de bootstrap (import estático — no hay dependencia circular) ──
import { loadConfig } from '../../src/bootstrap/config-loader';
import { detectProjectFiles } from '../../src/bootstrap/detector';

// ═══════════════════════════════════════════════════════════════════════════
//  1. TYPES
// ═══════════════════════════════════════════════════════════════════════════

describe('Types', () => {
  describe('FAILURE_TYPES_BY_DOMAIN', () => {
    it('should have exactly 5 domains', () => {
      const domains = Object.keys(FAILURE_TYPES_BY_DOMAIN);
      expect(domains).toEqual(['audit', 'test', 'commit', 'agent', 'bootstrap']);
    });

    it('should have at least 5 failure types per domain', () => {
      for (const [domain, types] of Object.entries(FAILURE_TYPES_BY_DOMAIN)) {
        expect(types.length).toBeGreaterThanOrEqual(5);
      }
    });

    it('should have unique failure types across all domains', () => {
      const allTypes = Object.values(FAILURE_TYPES_BY_DOMAIN).flat();
      const uniqueTypes = new Set(allTypes);
      expect(uniqueTypes.size).toBe(allTypes.length);
    });
  });

  describe('generateFailureId', () => {
    it('should generate IDs with fail_ prefix', () => {
      const id = generateFailureId();
      expect(id).toMatch(/^fail_/);
    });

    it('should generate unique IDs', () => {
      const ids = new Set(Array.from({ length: 100 }, () => generateFailureId()));
      expect(ids.size).toBe(100);
    });
  });

  describe('generatePolicyRuleId', () => {
    it('should generate POL-AUDI-001 format', () => {
      const id = generatePolicyRuleId('audit', 1);
      expect(id).toBe('POL-AUDI-001');
    });

    it('should generate POL-TEST-010 format', () => {
      const id = generatePolicyRuleId('test', 10);
      expect(id).toBe('POL-TEST-010');
    });

    it('should handle all domains', () => {
      expect(generatePolicyRuleId('commit', 1)).toBe('POL-COMM-001');
      expect(generatePolicyRuleId('agent', 1)).toBe('POL-AGEN-001');
      expect(generatePolicyRuleId('bootstrap', 1)).toBe('POL-BOOT-001');
    });
  });

  describe('defaultReflectionConfig', () => {
    it('should have promotion threshold of 3', () => {
      const config = defaultReflectionConfig();
      expect(config.promotionThreshold).toBe(3);
    });

    it('should have all domains active', () => {
      const config = defaultReflectionConfig();
      expect(config.activeDomains).toEqual(['audit', 'test', 'commit', 'agent', 'bootstrap']);
    });

    it('should have maxAutoGeneratedRules default of 20', () => {
      const config = defaultReflectionConfig();
      expect(config.maxAutoGeneratedRules).toBe(20);
    });
  });
});

// ═══════════════════════════════════════════════════════════════════════════
//  2. FAILURE CATALOG
// ═══════════════════════════════════════════════════════════════════════════

describe('FailureCatalog', () => {
  const testDir = path.join(os.tmpdir(), 'reflection-test-catalog');
  const catalog = new FailureCatalog({ projectRoot: testDir, useGlobalDir: false });

  afterAll(async () => {
    try { await fs.promises.rm(testDir, { recursive: true }); } catch {}
  });

  const sampleRecord: FailureRecord = {
    id: 'fail_test_001',
    domain: 'audit',
    failureType: 'connection_leak',
    severity: 'high',
    dimension: 'seguridad',
    gate: 'qa-engineer',
    agenteResponsable: 'qa',
    hallazgo: 'QueryRunner sin release en finally block',
    recomendacion: 'Agregar finally block con release()',
    archivos: ['src/database/connection.ts'],
    fecha: '2026-05-02T10:00:00.000Z',
  };

  beforeEach(async () => {
    try { await fs.promises.rm(testDir, { recursive: true }); } catch {}
    await catalog.load();
  });

  describe('CRUD', () => {
    it('should add a record', async () => {
      const added = await catalog.addRecord(sampleRecord);
      expect(added.id).toBe('fail_test_001');
      expect(await catalog.totalRecords()).toBe(1);
    });

    it('should get record by ID', async () => {
      await catalog.addRecord(sampleRecord);
      const found = await catalog.getRecordById('fail_test_001');
      expect(found).toBeDefined();
      expect(found?.failureType).toBe('connection_leak');
    });

    it('should update a record', async () => {
      await catalog.addRecord(sampleRecord);
      const updated = await catalog.updateRecord('fail_test_001', { severity: 'critical' });
      expect(updated).toBe(true);

      const record = await catalog.getRecordById('fail_test_001');
      expect(record?.severity).toBe('critical');
    });

    it('should delete a record', async () => {
      await catalog.addRecord(sampleRecord);
      const deleted = await catalog.deleteRecord('fail_test_001');
      expect(deleted).toBe(true);
      expect(await catalog.totalRecords()).toBe(0);
    });

    it('should mark as resolved', async () => {
      await catalog.addRecord(sampleRecord);
      const resolved = await catalog.markResolved('fail_test_001', 'abc123');
      expect(resolved).toBe(true);

      const record = await catalog.getRecordById('fail_test_001');
      expect(record?.resolvedByCommit).toBe('abc123');
      expect(record?.resolvedAt).toBeDefined();
    });
  });

  describe('Queries', () => {
    beforeEach(async () => {
      await catalog.addRecords([
        { ...sampleRecord, id: 'fail_001', domain: 'audit', failureType: 'connection_leak' },
        { ...sampleRecord, id: 'fail_002', domain: 'audit', failureType: 'security_vulnerability' },
        { ...sampleRecord, id: 'fail_003', domain: 'test', failureType: 'jest_timeout' },
        { ...sampleRecord, id: 'fail_004', domain: 'test', failureType: 'jest_timeout' },
      ]);
    });

    it('should find by domain', async () => {
      const auditRecords = await catalog.findByDomain('audit');
      expect(auditRecords).toHaveLength(2);
    });

    it('should find by domain and failureType', async () => {
      const records = await catalog.findByDomainAndType('test', 'jest_timeout');
      expect(records).toHaveLength(2);
    });

    it('should find unresolved records', async () => {
      const unresolved = await catalog.findUnresolved();
      expect(unresolved).toHaveLength(4);
    });

    it('should count by domain', async () => {
      const counts = await catalog.getDomainCounts();
      expect(counts.audit).toBe(2);
      expect(counts.test).toBe(2);
      expect(counts.commit).toBe(0);
    });
  });
});

// ═══════════════════════════════════════════════════════════════════════════
//  3. PATTERN DETECTOR
// ═══════════════════════════════════════════════════════════════════════════

describe('PatternDetector', () => {
  const testDir = path.join(os.tmpdir(), 'reflection-test-patterns');
  const catalog = new FailureCatalog({ projectRoot: testDir, useGlobalDir: false });
  const detector = new PatternDetector(catalog);

  afterAll(async () => {
    try { await fs.promises.rm(testDir, { recursive: true }); } catch {}
  });

  beforeEach(async () => {
    try { await fs.promises.rm(testDir, { recursive: true }); } catch {}
    await catalog.load();
  });

  it('should detect no patterns with less than threshold', async () => {
    await catalog.addRecords([
      { id: '1', domain: 'audit', failureType: 'connection_leak', severity: 'high', dimension: 'seguridad', gate: 'qa', agenteResponsable: 'qa', hallazgo: 'test', recomendacion: 'fix', archivos: [], fecha: '2026-01-01' },
      { id: '2', domain: 'audit', failureType: 'connection_leak', severity: 'high', dimension: 'seguridad', gate: 'qa', agenteResponsable: 'qa', hallazgo: 'test', recomendacion: 'fix', archivos: [], fecha: '2026-01-02' },
    ]);
    const patterns = await detector.scan(3);
    expect(patterns).toHaveLength(0);
  });

  it('should detect pattern with 3+ occurrences', async () => {
    await catalog.addRecords([
      { id: '1', domain: 'audit', failureType: 'connection_leak', severity: 'high', dimension: 'seguridad', gate: 'qa', agenteResponsable: 'qa', hallazgo: 'test', recomendacion: 'fix', archivos: [], fecha: '2026-01-01' },
      { id: '2', domain: 'audit', failureType: 'connection_leak', severity: 'high', dimension: 'seguridad', gate: 'qa', agenteResponsable: 'qa', hallazgo: 'test', recomendacion: 'fix', archivos: [], fecha: '2026-01-02' },
      { id: '3', domain: 'audit', failureType: 'connection_leak', severity: 'high', dimension: 'seguridad', gate: 'qa', agenteResponsable: 'qa', hallazgo: 'test', recomendacion: 'fix', archivos: [], fecha: '2026-01-03' },
    ]);
    const patterns = await detector.scan(3);
    expect(patterns).toHaveLength(1);
    expect(patterns[0].failureType).toBe('connection_leak');
    expect(patterns[0].count).toBe(3);
    expect(patterns[0].promotedToPolicy).toBe(false);
  });

  it('should detect patterns by domain only', async () => {
    await catalog.addRecords([
      { id: '1', domain: 'audit', failureType: 'connection_leak', severity: 'high', dimension: 'seguridad', gate: 'qa', agenteResponsable: 'qa', hallazgo: 'test', recomendacion: 'fix', archivos: [], fecha: '2026-01-01' },
      { id: '2', domain: 'audit', failureType: 'connection_leak', severity: 'high', dimension: 'seguridad', gate: 'qa', agenteResponsable: 'qa', hallazgo: 'test', recomendacion: 'fix', archivos: [], fecha: '2026-01-02' },
      { id: '3', domain: 'audit', failureType: 'connection_leak', severity: 'high', dimension: 'seguridad', gate: 'qa', agenteResponsable: 'qa', hallazgo: 'test', recomendacion: 'fix', archivos: [], fecha: '2026-01-03' },
      { id: '4', domain: 'test', failureType: 'jest_timeout', severity: 'high', dimension: 'rendimiento', gate: 'jest', agenteResponsable: 'system', hallazgo: 'test', recomendacion: 'fix', archivos: [], fecha: '2026-01-01' },
      { id: '5', domain: 'test', failureType: 'jest_timeout', severity: 'high', dimension: 'rendimiento', gate: 'jest', agenteResponsable: 'system', hallazgo: 'test', recomendacion: 'fix', archivos: [], fecha: '2026-01-02' },
      { id: '6', domain: 'test', failureType: 'jest_timeout', severity: 'high', dimension: 'rendimiento', gate: 'jest', agenteResponsable: 'system', hallazgo: 'test', recomendacion: 'fix', archivos: [], fecha: '2026-01-03' },
    ]);
    const auditPatterns = await detector.scanByDomain('audit', 3);
    expect(auditPatterns).toHaveLength(1);
    expect(auditPatterns[0].domain).toBe('audit');

    const testPatterns = await detector.scanByDomain('test', 3);
    expect(testPatterns).toHaveLength(1);
    expect(testPatterns[0].domain).toBe('test');
  });

  it('should find near-miss patterns (count = threshold - 1)', async () => {
    await catalog.addRecords([
      { id: '1', domain: 'audit', failureType: 'connection_leak', severity: 'high', dimension: 'seguridad', gate: 'qa', agenteResponsable: 'qa', hallazgo: 'test', recomendacion: 'fix', archivos: [], fecha: '2026-01-01' },
      { id: '2', domain: 'audit', failureType: 'connection_leak', severity: 'high', dimension: 'seguridad', gate: 'qa', agenteResponsable: 'qa', hallazgo: 'test', recomendacion: 'fix', archivos: [], fecha: '2026-01-02' },
    ]);
    const nearMiss = await detector.getNearMissPatterns(3);
    expect(nearMiss.length).toBeGreaterThanOrEqual(1);
  });

  it('should sort patterns by count descending', async () => {
    await catalog.addRecords([
      { id: '1', domain: 'audit', failureType: 'connection_leak', severity: 'high', dimension: 'seguridad', gate: 'qa', agenteResponsable: 'qa', hallazgo: 'test', recomendacion: 'fix', archivos: [], fecha: '2026-01-01' },
      { id: '2', domain: 'audit', failureType: 'connection_leak', severity: 'high', dimension: 'seguridad', gate: 'qa', agenteResponsable: 'qa', hallazgo: 'test', recomendacion: 'fix', archivos: [], fecha: '2026-01-02' },
      { id: '3', domain: 'audit', failureType: 'connection_leak', severity: 'high', dimension: 'seguridad', gate: 'qa', agenteResponsable: 'qa', hallazgo: 'test', recomendacion: 'fix', archivos: [], fecha: '2026-01-03' },
      { id: '4', domain: 'test', failureType: 'jest_timeout', severity: 'high', dimension: 'rendimiento', gate: 'jest', agenteResponsable: 'system', hallazgo: 'test', recomendacion: 'fix', archivos: [], fecha: '2026-01-01' },
      { id: '5', domain: 'test', failureType: 'jest_timeout', severity: 'high', dimension: 'rendimiento', gate: 'jest', agenteResponsable: 'system', hallazgo: 'test', recomendacion: 'fix', archivos: [], fecha: '2026-01-02' },
      { id: '6', domain: 'test', failureType: 'jest_timeout', severity: 'high', dimension: 'rendimiento', gate: 'jest', agenteResponsable: 'system', hallazgo: 'test', recomendacion: 'fix', archivos: [], fecha: '2026-01-03' },
      { id: '7', domain: 'test', failureType: 'jest_timeout', severity: 'high', dimension: 'rendimiento', gate: 'jest', agenteResponsable: 'system', hallazgo: 'test', recomendacion: 'fix', archivos: [], fecha: '2026-01-01' },
    ]);
    const patterns = await detector.scan(3);
    expect(patterns[0].count).toBeGreaterThanOrEqual(patterns[1]?.count ?? 0);
  });
});

// ═══════════════════════════════════════════════════════════════════════════
//  4. POLICY PROMOTER
// ═══════════════════════════════════════════════════════════════════════════

describe('PolicyPromoter', () => {
  const testDir = path.join(os.tmpdir(), 'reflection-test-promoter');
  const manifestPath = path.join(testDir, 'manifest.yaml');

  const promoter = new PolicyPromoter({ manifestPath });

  afterAll(async () => {
    try { await fs.promises.rm(testDir, { recursive: true }); } catch {}
  });

  beforeEach(async () => {
    try { await fs.promises.rm(testDir, { recursive: true }); } catch {}
    await fs.promises.mkdir(testDir, { recursive: true });
  });

  const samplePattern: DetectedPattern = {
    failureType: 'connection_leak',
    domain: 'audit',
    count: 3,
    firstSeen: '2026-01-01',
    lastSeen: '2026-01-03',
    severity: 'high',
    recordIds: ['1', '2', '3'],
    dominantDimension: 'seguridad',
    dominantGate: 'qa',
    recommendedAction: 'Agregar finally block con release()',
    promotedToPolicy: false,
  };

  it('should promote a pattern to policyRule', async () => {
    const rule = await promoter.promote(samplePattern);
    expect(rule.id).toMatch(/^POL-AUDI-\d+$/);
    expect(rule.autoGenerated).toBe(true);
    expect(rule.trigger.domain).toBe('audit');
    expect(rule.trigger.pattern).toBe('connection_leak');
    expect(rule.name).toContain('Connection Leak');
  });

  it('should persist rules across reads', async () => {
    await promoter.promote(samplePattern);
    const rules = await promoter.getExistingRules();
    expect(rules.length).toBeGreaterThanOrEqual(1);
    expect(rules[0].id).toMatch(/^POL-AUDI-\d+$/);
  });

  it('should generate sequential IDs', async () => {
    const rule1 = await promoter.promote(samplePattern);
    const rule2 = await promoter.promote({ ...samplePattern, failureType: 'security_vulnerability' });
    const num1 = parseInt(rule1.id.split('-')[2]);
    const num2 = parseInt(rule2.id.split('-')[2]);
    expect(num2).toBeGreaterThan(num1);
  });

  it('should remove a rule by ID', async () => {
    const rule = await promoter.promote(samplePattern);
    const removed = await promoter.removeRule(rule.id);
    expect(removed).toBe(true);

    const rules = await promoter.getExistingRules();
    expect(rules.find(r => r.id === rule.id)).toBeUndefined();
  });

  it('should update an existing rule', async () => {
    const rule = await promoter.promote(samplePattern);
    samplePattern.promotedToPolicy = true;

    const updatedRule = await promoter.promote({ ...samplePattern, count: 5 }, rule.id);
    expect(updatedRule.id).toBe(rule.id);

    const manifest = await promoter.readManifest();
    const found = manifest.policyRules.find((r: any) => r.id === rule.id);
    expect(found).toBeDefined();
  });

  it('should write valid YAML', async () => {
    await promoter.promote(samplePattern);
    const content = await fs.promises.readFile(manifestPath, 'utf-8');
    expect(content).toContain('policyRules:');
    expect(content).toContain('POL-AUDI');
    expect(content).toContain('autoGenerated: true');
  });
});

// ═══════════════════════════════════════════════════════════════════════════
//  5. REFLECTION ENGINE (pipeline completo)
// ═══════════════════════════════════════════════════════════════════════════

describe('ReflectionEngine', () => {
  const testDir = path.join(os.tmpdir(), 'reflection-test-engine');
  let engine: ReflectionEngine;

  beforeEach(async () => {
    try { await fs.promises.rm(testDir, { recursive: true }); } catch {}
    engine = new ReflectionEngine({
      projectRoot: testDir,
      useGlobalDir: false,
      config: { autoPromote: true },
    });
    await engine.initialize();
  });

  afterAll(async () => {
    try { await fs.promises.rm(testDir, { recursive: true }); } catch {}
  });

  it('should initialize with empty catalog', async () => {
    const stats = await engine.getStats();
    expect(stats.totalIncidents).toBe(0);
    expect(stats.enabled).toBe(true);
  });

  it('should report incident and detect patterns', async () => {
    // Reportar 3 incidentes del mismo tipo
    for (let i = 0; i < 3; i++) {
      await engine.reportIncident({
        domain: 'audit',
        failureType: 'connection_leak',
        severity: 'high',
        dimension: 'seguridad',
        gate: 'qa-engineer',
        agenteResponsable: 'qa',
        hallazgo: `QueryRunner sin release #${i}`,
        recomendacion: 'Agregar finally block',
        archivos: ['connection.ts'],
        fecha: new Date().toISOString(),
      });
    }

    // Ejecutar reflexión
    const { patterns, promotedRules } = await engine.reflect();

    // Debería detectar el patrón
    expect(patterns.length).toBeGreaterThanOrEqual(1);
    const leakPattern = patterns.find(p => p.failureType === 'connection_leak');
    expect(leakPattern).toBeDefined();
    expect(leakPattern!.count).toBe(3);

    // Debería promover automáticamente
    if (engine['config'].autoPromote) {
      expect(promotedRules.length).toBeGreaterThanOrEqual(1);
    }
  });

  it('should get stats after incidents', async () => {
    await engine.reportIncident({
      domain: 'audit', failureType: 'connection_leak', severity: 'high', dimension: 'seguridad',
      gate: 'qa', agenteResponsable: 'qa', hallazgo: 'test', recomendacion: 'fix',
      archivos: [], fecha: new Date().toISOString(),
    });
    await engine.reportIncident({
      domain: 'test', failureType: 'jest_timeout', severity: 'high', dimension: 'rendimiento',
      gate: 'jest', agenteResponsable: 'system', hallazgo: 'test', recomendacion: 'fix',
      archivos: [], fecha: new Date().toISOString(),
    });

    const stats = await engine.getStats();
    expect(stats.totalIncidents).toBe(2);
    expect(stats.countsByDomain.audit).toBe(1);
    expect(stats.countsByDomain.test).toBe(1);
  });

  it('should report incident and return patterns', async () => {
    const result = await engine.reportIncident({
      domain: 'audit', failureType: 'connection_leak', severity: 'high', dimension: 'seguridad',
      gate: 'qa', agenteResponsable: 'qa', hallazgo: 'test', recomendacion: 'fix',
      archivos: [], fecha: new Date().toISOString(),
    });

    expect(result.record.id).toMatch(/^fail_/);
    expect(result.record.domain).toBe('audit');
    expect(result.record.failureType).toBe('connection_leak');
  });
});

// ═══════════════════════════════════════════════════════════════════════════
//  6. DOMINIOS
// ═══════════════════════════════════════════════════════════════════════════

describe('Dominios (failureType detection)', () => {
  describe('AuditDomain', () => {
    it('should detect connection_leak', () => {
      expect(detectAuditFailureType('QueryRunner sin release en finally')).toBe('connection_leak');
      expect(detectAuditFailureType('Conexión no liberada correctamente')).toBe('connection_leak');
    });

    it('should detect security_vulnerability', () => {
      expect(detectAuditFailureType('Vulnerabilidad de SQL injection detectada')).toBe('security_vulnerability');
    });

    it('should detect missing_test_coverage', () => {
      expect(detectAuditFailureType('Sin test coverage para este flujo')).toBe('missing_test_coverage');
    });

    it('should return fallback for unknown text', () => {
      expect(detectAuditFailureType('texto sin patrón conocido')).toBe('incomplete_error_handling');
    });

    it('should have metadata for all failureTypes', () => {
      for (const meta of FAILURE_TYPES_BY_DOMAIN.audit) {
        const metaData = getAuditFailureTypeMeta(meta);
        if (meta !== 'incomplete_error_handling') {
          // incomplete_error_handling es el fallback, no tiene meta propia
          expect(metaData).toBeDefined();
        }
      }
    });
  });

  describe('TestDomain', () => {
    it('should detect tsc_noEmit_type_error', () => {
      expect(detectTestFailureType('Error TS2345: Property X does not exist')).toBe('tsc_noEmit_type_error');
      expect(detectTestFailureType('Typecheck falló con error de tipos')).toBe('tsc_noEmit_type_error');
    });

    it('should detect jest_timeout', () => {
      expect(detectTestFailureType('Test timed out after 5000ms')).toBe('jest_timeout');
    });

    it('should detect coverage_below_threshold', () => {
      expect(detectTestFailureType('Statements 65% below 80% threshold')).toBe('coverage_below_threshold');
    });

    it('should detect flaky_test', () => {
      expect(detectTestFailureType('Test intermitente falla a veces')).toBe('flaky_test');
    });
  });

  describe('CommitDomain', () => {
    it('should detect missing_type', () => {
      expect(detectCommitFailureType('Mensaje sin tipo conventional commit')).toBe('missing_type');
    });

    it('should detect typecheck_failed_before_commit', () => {
      expect(detectCommitFailureType('Typecheck failed antes del commit')).toBe('typecheck_failed_before_commit');
    });

    it('should detect test_failed_before_commit', () => {
      expect(detectCommitFailureType('Tests fallidos antes del commit')).toBe('test_failed_before_commit');
    });

    it('should detect branch_naming_invalid', () => {
      expect(detectCommitFailureType('Nombre de rama inválido')).toBe('branch_naming_invalid');
    });
  });

  describe('AgentDomain', () => {
    it('should detect wrong_agent_selected', () => {
      expect(detectAgentFailureType('Se seleccionó agente incorrecto para seguridad')).toBe('wrong_agent_selected');
    });

    it('should detect agent_hallucination', () => {
      expect(detectAgentFailureType('Alucinación: inventó una API que no existe')).toBe('agent_hallucination');
    });

    it('should detect tool_execution_failed', () => {
      expect(detectAgentFailureType('Tool execution failed con error ENOENT')).toBe('tool_execution_failed');
    });
  });

  describe('BootstrapDomain', () => {
    it('should detect missing_config_yaml', () => {
      expect(detectBootstrapFailureType('Missing config.yaml no encontrado')).toBe('missing_config_yaml');
    });

    it('should detect manifest_corrupt', () => {
      expect(detectBootstrapFailureType('Manifest.yaml corrupto: error al parsear')).toBe('manifest_corrupt');
    });

    it('should detect memory_load_failure', () => {
      expect(detectBootstrapFailureType('Memory load failure: no se pudo cargar')).toBe('memory_load_failure');
    });
  });
});

// ═══════════════════════════════════════════════════════════════════════════
//  7. HOOKS
// ═══════════════════════════════════════════════════════════════════════════

describe('Hooks', () => {
  const testDir = path.join(os.tmpdir(), 'reflection-test-hooks');
  let engine: ReflectionEngine;

  beforeEach(async () => {
    try { await fs.promises.rm(testDir, { recursive: true }); } catch {}
    engine = new ReflectionEngine({ projectRoot: testDir, useGlobalDir: false });
    await engine.initialize();
  });

  afterAll(async () => {
    try { await fs.promises.rm(testDir, { recursive: true }); } catch {}
  });

  describe('AuditHook', () => {
    it('should report an AuditFinding to the engine', async () => {
      const hook = new AuditHook(engine);
      const finding = {
        id: 'finding-001',
        dimension: 'seguridad',
        hallazgo: 'QueryRunner sin release en finally block',
        severidad: 'high' as const,
        evidencia: 'src/database/connection.ts',
        recomendacion: 'Agregar finally block',
        agenteResponsable: 'qa',
      };

      const result = await hook.reportFinding(finding, 'qa-engineer');
      expect(result.record.domain).toBe('audit');
      expect(result.record.failureType).toBe('connection_leak');
    });

    it('should report multiple findings in batch', async () => {
      const hook = new AuditHook(engine);
      const findings = [
        { id: '1', dimension: 'seguridad', hallazgo: 'Connection leak', severidad: 'high' as const, evidencia: 'file.ts', recomendacion: 'fix', agenteResponsable: 'qa' },
        { id: '2', dimension: 'calidad', hallazgo: 'Missing test coverage', severidad: 'medium' as const, evidencia: 'file.ts', recomendacion: 'add tests', agenteResponsable: 'qa' },
      ];

      const results = await hook.reportFindings(findings, 'qa-engineer');
      expect(results).toHaveLength(2);
    });

    it('should reflect the audit domain', async () => {
      const hook = new AuditHook(engine);
      await hook.reportFinding(
        { id: '1', dimension: 'seguridad', hallazgo: 'Connection leak', severidad: 'high' as const, evidencia: 'file.ts', recomendacion: 'fix', agenteResponsable: 'qa' },
        'qa-engineer'
      );

      const stats = await hook.getAuditStats();
      expect(stats.totalIncidents).toBeGreaterThanOrEqual(1);
    });
  });

  describe('TestHook', () => {
    it('should report a test failure', async () => {
      const hook = new TestHook(engine);
      const result = await hook.reportTestFailure('Error TS2345: Property X does not exist', ['src/file.ts']);
      expect(result.record.domain).toBe('test');
      expect(result.record.failureType).toBe('tsc_noEmit_type_error');
    });

    it('should report coverage failure', async () => {
      const hook = new TestHook(engine);
      const result = await hook.reportCoverageFailure('80%', '65%', ['src/file.ts']);
      expect(result.record.failureType).toBe('coverage_below_threshold');
    });

    it('should report flaky test', async () => {
      const hook = new TestHook(engine);
      const result = await hook.reportFlakyTest('UserService.spec.ts', '3/10', ['src/user.service.ts']);
      expect(result.record.failureType).toBe('flaky_test');
    });
  });

  describe('CommitHook', () => {
    it('should report a commit validation failure', async () => {
      const hook = new CommitHook(engine);
      const result = await hook.reportCommitFailure('Mensaje sin tipo conventional commit', ['src/file.ts']);
      expect(result.record.domain).toBe('commit');
      expect(result.record.failureType).toBe('missing_type');
    });

    it('should report typecheck failure', async () => {
      const hook = new CommitHook(engine);
      const result = await hook.reportTypecheckFailure('TypeScript error TS2322', ['src/types.ts']);
      expect(result.record.failureType).toBe('typecheck_failed_before_commit');
    });

    it('should report test failure during commit', async () => {
      const hook = new CommitHook(engine);
      const result = await hook.reportTestFailure('Test "should login" failed', ['src/auth.spec.ts']);
      expect(result.record.failureType).toBe('test_failed_before_commit');
    });
  });

  describe('AgentHook', () => {
    it('should report an agent failure', async () => {
      const hook = new AgentHook(engine);
      const result = await hook.reportAgentFailure('Se seleccionó agente incorrecto para seguridad', 'orchestrator');
      expect(result.record.domain).toBe('agent');
    });

    it('should report hallucination', async () => {
      const hook = new AgentHook(engine);
      const result = await hook.reportHallucination('agent-1', 'Aquí está la API que no existe', 'inventó método');
      expect(result.record.failureType).toBe('agent_hallucination');
    });

    it('should report timeout', async () => {
      const hook = new AgentHook(engine);
      const result = await hook.reportTimeout('agent-1', 'analizar 1000 archivos');
      expect(result.record.failureType).toBe('agent_timeout');
    });

    it('should report wrong agent selection', async () => {
      const hook = new AgentHook(engine);
      const result = await hook.reportWrongAgentSelection('general', 'security');
      expect(result.record.failureType).toBe('wrong_agent_selected');
    });
  });

  describe('BootstrapHook', () => {
    it('should report a bootstrap failure', async () => {
      const hook = new BootstrapHook(engine);
      const result = await hook.reportBootstrapFailure('No se encontró config.yaml', ['config.yaml']);
      expect(result.record.domain).toBe('bootstrap');
      expect(result.record.failureType).toBe('missing_config_yaml');
    });

    it('should report manifest corrupt', async () => {
      const hook = new BootstrapHook(engine);
      const result = await hook.reportManifestCorrupt('Error al parsear YAML', 'manifest.yaml');
      expect(result.record.failureType).toBe('manifest_corrupt');
    });

    it('should report memory load failure', async () => {
      const hook = new BootstrapHook(engine);
      const result = await hook.reportMemoryLoadFailure('memory/session.md', 'Archivo no encontrado');
      expect(result.record.failureType).toBe('memory_load_failure');
    });
  });
});

// ═══════════════════════════════════════════════════════════════════════════
//  8. INTEGRACIÓN
// ═══════════════════════════════════════════════════════════════════════════

describe('Integración AuditReporter → ReflectionEngine', () => {
  const testDir = path.join(os.tmpdir(), 'reflection-test-integration');
  let engine: ReflectionEngine;
  // Usar require dinámico para evitar import circular
  let AuditReporter: any;

  beforeAll(async () => {
    // Import dinámico del AuditReporter
    const mod = await import('../../src/orchestrator/audit-reporter');
    AuditReporter = mod.AuditReporter;
  });

  beforeEach(async () => {
    try { await fs.promises.rm(testDir, { recursive: true }); } catch {}
    engine = new ReflectionEngine({ projectRoot: testDir, useGlobalDir: false });
    await engine.initialize();
  });

  afterAll(async () => {
    try { await fs.promises.rm(testDir, { recursive: true }); } catch {}
  });

  it('should connect AuditReporter to ReflectionEngine', () => {
    const reporter = new AuditReporter({ projectRoot: testDir, useGlobalDir: false });
    expect(() => reporter.connectReflectionEngine(engine)).not.toThrow();
  });

  it('should report findings via completeSprint', async () => {
    const reporter = new AuditReporter({ projectRoot: testDir, useGlobalDir: false });
    reporter.connectReflectionEngine(engine);

    // Reportar un gate con hallazgo
    await reporter.recordGate('qa', 'qa-engineer', 'NO-GO condicional', [
      {
        id: 'finding-1',
        dimension: 'seguridad',
        hallazgo: 'QueryRunner sin release en finally',
        severidad: 'high',
        evidencia: 'src/db/conn.ts',
        recomendacion: 'Agregar finally block',
        agenteResponsable: 'qa',
      },
    ]);

    // Completar sprint (esto llama reportToReflectionEngine internamente)
    await reporter.completeSprint({
      name: 'Sprint-1',
      version: '1.0.0',
      purpose: 'Test',
      newFiles: [],
      modifiedFiles: [],
      testCount: 0,
      testTime: '0s',
    });

    // Verificar que los hallazgos llegaron al engine
    const stats = await engine.getStats();
    expect(stats.totalIncidents).toBeGreaterThanOrEqual(1);
  });

  it('should connect ResponseEvaluator to ReflectionEngine', () => {
    const AgentClient = require('../../src/api/client').AgentClient;
    const client = new AgentClient({ apiKey: 'test' });
    const evaluator = new (require('../../src/agent/evaluation').ResponseEvaluator)(client);
    expect(() => evaluator.connectReflectionEngine(engine)).not.toThrow();
  });
});

// ═══════════════════════════════════════════════════════════════════════════
//  9. PERSISTENCIA EN DISCO (failures.json)
// ═══════════════════════════════════════════════════════════════════════════

describe('Persistencia en disco (failures.json)', () => {
  const testDir = path.join(os.tmpdir(), 'reflection-test-persistence');
  let engine: ReflectionEngine;

  beforeEach(async () => {
    try { await fs.promises.rm(testDir, { recursive: true }); } catch {}
    engine = new ReflectionEngine({ projectRoot: testDir, useGlobalDir: false });
    await engine.initialize();
  });

  afterAll(async () => {
    try { await fs.promises.rm(testDir, { recursive: true }); } catch {}
  });

  it('should persist incidentes de BootstrapHook al disco via ReflectionEngine', async () => {
    const hook = new BootstrapHook(engine);

    // Reportar 3 incidentes de bootstrap
    await hook.reportBootstrapFailure('No se encontró config.yaml', ['config.yaml']);
    await hook.reportManifestCorrupt('Error al parsear YAML', 'manifest.yaml');
    await hook.reportMemoryLoadFailure('memory/session.md', 'Archivo no encontrado');

    // Verificar que el archivo failures.json existe en disco
    const catalog = engine.getCatalog();
    const catalogPath = catalog.getCatalogPath();
    const content = await fs.promises.readFile(catalogPath, 'utf-8');
    const records = JSON.parse(content) as any[];

    expect(records.length).toBeGreaterThanOrEqual(3);

    // Verificar estructura correcta
    const bootstrapRecords = records.filter((r: any) => r.domain === 'bootstrap');
    expect(bootstrapRecords.length).toBeGreaterThanOrEqual(3);

    // Verificar tipos de fallo específicos
    const failureTypes = bootstrapRecords.map((r: any) => r.failureType);
    expect(failureTypes).toContain('missing_config_yaml');
    expect(failureTypes).toContain('manifest_corrupt');
    expect(failureTypes).toContain('memory_load_failure');

    // Verificar campos requeridos en cada registro
    for (const record of bootstrapRecords) {
      expect(record.id).toBeDefined();
      expect(record.domain).toBe('bootstrap');
      expect(record.failureType).toBeDefined();
      expect(record.severity).toBeDefined();
      expect(record.hallazgo).toBeDefined();
      expect(record.recomendacion).toBeDefined();
      expect(record.fecha).toBeDefined();
    }
  });

  it('should persist incidentes de todos los dominios y poder leerlos del archivo', async () => {
    const hook = new BootstrapHook(engine);

    // Reportar incidentes de diferentes tipos
    await hook.reportBootstrapFailure('No se encontró config.yaml', ['config.yaml']);
    await hook.reportManifestCorrupt('Error al parsear YAML', 'manifest.yaml');

    // También reportar incidente de auditoría via engine directo
    await engine.reportIncident({
      domain: 'audit',
      failureType: 'connection_leak',
      severity: 'high',
      dimension: 'seguridad',
      gate: 'qa-engineer',
      agenteResponsable: 'qa',
      hallazgo: 'QueryRunner sin release',
      recomendacion: 'Agregar finally block',
      archivos: ['connection.ts'],
      fecha: new Date().toISOString(),
    });

    // Leer el archivo directamente
    const catalog = engine.getCatalog();
    const catalogPath = catalog.getCatalogPath();
    const content = await fs.promises.readFile(catalogPath, 'utf-8');
    const records = JSON.parse(content) as any[];

    expect(records.length).toBe(3);

    // Verificar distribución por dominio
    const domains = records.map((r: any) => r.domain);
    expect(domains.filter((d: string) => d === 'bootstrap')).toHaveLength(2);
    expect(domains.filter((d: string) => d === 'audit')).toHaveLength(1);
  });

  it('should mantener integridad del archivo JSON en escrituras sucesivas', async () => {
    const hook = new BootstrapHook(engine);

    // Primera escritura
    await hook.reportBootstrapFailure('Error #1', ['file1.yaml']);
    let content = await fs.promises.readFile(engine.getCatalog().getCatalogPath(), 'utf-8');
    let records = JSON.parse(content);
    expect(records).toHaveLength(1);

    // Segunda escritura
    await hook.reportManifestCorrupt('Error #2', 'manifest.yaml');
    content = await fs.promises.readFile(engine.getCatalog().getCatalogPath(), 'utf-8');
    records = JSON.parse(content);
    expect(records).toHaveLength(2);

    // Tercera escritura
    await hook.reportMemoryLoadFailure('session.md', 'Error #3');
    content = await fs.promises.readFile(engine.getCatalog().getCatalogPath(), 'utf-8');
    records = JSON.parse(content);
    expect(records).toHaveLength(3);

    // Verificar que todos los registros se mantienen
    expect(records[0].hallazgo).toContain('Error #1');
    expect(records[1].hallazgo).toContain('Error #2');
    expect(records[2].hallazgo).toContain('Error #3');
  });
});

// ═══════════════════════════════════════════════════════════════════════════
//  10. INTEGRACIÓN BOOTSTRAP LOADERS → REFLECTION ENGINE
// ═══════════════════════════════════════════════════════════════════════════

describe('Integración Bootstrap Loaders → ReflectionEngine', () => {
  const testDir = path.join(os.tmpdir(), 'reflection-test-loaders');
  let engine: ReflectionEngine;
  let hook: BootstrapHook;

  beforeEach(async () => {
    try { await fs.promises.rm(testDir, { recursive: true }); } catch {}
    engine = new ReflectionEngine({ projectRoot: testDir, useGlobalDir: false });
    await engine.initialize();
    hook = new BootstrapHook(engine);
  });

  afterAll(async () => {
    try { await fs.promises.rm(testDir, { recursive: true }); } catch {}
  });

  it('config-loader debe reportar missing config cuando el archivo no existe', async () => {
    // Cargar con hook — archivo inexistente
    const config = await loadConfig(path.join(testDir, '_no-existe_.yaml'), { hook });

    // Debe retornar null
    expect(config).toBeNull();

    // El engine debe tener 1 incidente de bootstrap
    const stats = await engine.getStats();
    expect(stats.totalIncidents).toBe(1);

    // Verificar que se persistió en disco
    const catalog = engine.getCatalog();
    const records = await catalog.findByDomain('bootstrap');
    expect(records.length).toBe(1);
    expect(records[0].failureType).toBe('missing_config_yaml');
    expect(records[0].archivos.some((f: string) => f.includes('_no-existe_'))).toBe(true);
  });

  it('config-loader debe reportar manifest corrupt cuando el YAML es inválido', async () => {
    // Crear directorio y un archivo YAML inválido
    await fs.promises.mkdir(testDir, { recursive: true });
    const badYamlPath = path.join(testDir, 'bad-config.yaml');
    await fs.promises.writeFile(badYamlPath, '{{{invalid: yaml: [[[', 'utf-8');

    const config = await loadConfig(badYamlPath, { hook });

    // Debe retornar null
    expect(config).toBeNull();

    // El engine debe tener 1 incidente de manifest corrupt
    const records = await engine.getCatalog().findByDomain('bootstrap');
    expect(records.length).toBe(1);

    // yaml.parse lanza error (no ENOENT) → reportManifestCorrupt → manifest_corrupt
    expect(records[0].failureType).toBe('manifest_corrupt');
  });

  it('detector debe reportar missing config cuando no existe .ai-assistant', async () => {
    // Detectar en un directorio sin .ai-assistant
    const result = await detectProjectFiles(testDir, { hook });

    // Debe reportar que no existe
    expect(result.exists).toBe(false);

    // El engine debe tener un incidente de bootstrap
    const records = await engine.getCatalog().findByDomain('bootstrap');
    expect(records.length).toBeGreaterThanOrEqual(1);

    // Verificar que se reportó como missing_config_yaml
    const configRecords = records.filter((r: any) =>
      r.failureType === 'missing_config_yaml' && r.hallazgo.includes(testDir)
    );
    expect(configRecords.length).toBeGreaterThanOrEqual(1);
  });

  it('loader con hook undefined no debe fallar', async () => {
    // Pasar hook undefined, debe funcionar sin error
    const config = await loadConfig(path.join(testDir, '_no-existe_.yaml'), { hook: undefined });
    expect(config).toBeNull();

    // No debe haber incidentes
    const stats = await engine.getStats();
    expect(stats.totalIncidents).toBe(0);
  });
});
